### ISSUE TITLE
Export config to own repository

### ISSUE THREAD

**Issue by spookykidmm** [jkientzler/pantheon-revenge-iso#1]
Hello, my name is Josiah Ward, and I am one of the developers at revenge. I am very interested in seeing your configuration of Pantheon and was possibly even thinking you could push it to it's own github repository so I can browse it?
Thank you,
Josiah Ward

**Comment by jkientzler** [comment]
Hi Josiah! I actually really need to take this repo down. Sorry to be getting back to you so late about it. This was a bit of a side project that I attempted, but it didn't work out as far as I can remember.
